files:
  - source: /app/src/main/res/values/strings*.xml
    translation: /app/src/main/res/values-%android_code%/%original_file_name%
    languages_mapping:
      android_code:
        ml-IN: ml
        sv-SE: sv
        es-ES: es
        de: de
        ru: ru
        pl: pl
        ja: ja
        it: it
        fr: fr
        da: da
        kn: kn
        nl: nl
        hu: hu
        cs: cs
        ko: ko
        gl: gl
        sc: sc
        kab: kab
    translate_attributes: 0
